import type { TemplateConfig } from "@/types/invitation";

export const TEMPLATES: Record<string, TemplateConfig> = {
  elegant: {
    id: "tpl-elegant",
    slug: "elegant",
    name: "01 Elegant",
    description: "Desain anggun dengan tipografi serif klasik, palet warna krem & emas hangat, serta amplop 3D unboxing dengan segel lilin wax rose gold.",
    colors: {
      primary: "#8a6d3b",
      secondary: "#c5a059",
      background: "#fdfbf7",
      foreground: "#2b2623",
      accent: "#f4ede2",
    },
    typography: {
      heading: "serif",
      body: "sans",
    },
    sections: [
      "cover",
      "opening",
      "couple",
      "event",
      "countdown",
      "location",
      "story",
      "gallery",
      "gift",
      "rsvp",
      "guestbook",
      "closing",
    ],
    animationStyle: "fade-up",
    ornamentStyle: "floral-gold",
  },
  minimalist: {
    id: "tpl-minimalist",
    slug: "minimalist",
    name: "02 Minimalist",
    description: "Desain kontemporer bersih dengan tipografi sans-serif modern, tata letak luas, nuansa monokromatik abu-abu halus dan hitam pekat.",
    colors: {
      primary: "#18181b",
      secondary: "#71717a",
      background: "#ffffff",
      foreground: "#09090b",
      accent: "#f4f4f5",
    },
    typography: {
      heading: "sans",
      body: "sans",
    },
    sections: [
      "cover",
      "opening",
      "couple",
      "event",
      "countdown",
      "location",
      "story",
      "gallery",
      "gift",
      "rsvp",
      "guestbook",
      "closing",
    ],
    animationStyle: "slide",
    ornamentStyle: "geometric",
  },
  nusantara: {
    id: "tpl-nusantara",
    slug: "nusantara",
    name: "03 Nusantara",
    description: "Desain berbalut kekayaan budaya Nusantara dengan ornamen motif tradisional terakota, cokelat kayu jati, segel lilin perunggu, dan gunungan wayang interaktif.",
    colors: {
      primary: "#7c2d12",
      secondary: "#b45309",
      background: "#fcfaf7",
      foreground: "#291b12",
      accent: "#fef3c7",
    },
    typography: {
      heading: "serif",
      body: "sans",
    },
    sections: [
      "cover",
      "opening",
      "couple",
      "event",
      "countdown",
      "location",
      "story",
      "gallery",
      "gift",
      "rsvp",
      "guestbook",
      "closing",
    ],
    animationStyle: "smooth",
    ornamentStyle: "batik-accent",
  },
  celestial: {
    id: "tpl-celestial",
    slug: "celestial",
    name: "04 Celestial Midnight",
    description: "Konsep Dark Luxury spektakuler dengan latar beludru hitam obsidian, kilauan stardust emas 3D, dan amplop obsidian mewah dengan segel lilin emas murni.",
    colors: {
      primary: "#d4af37",
      secondary: "#e0c36b",
      background: "#08080c",
      foreground: "#f4f4f8",
      accent: "#13131c",
    },
    typography: {
      heading: "serif",
      body: "sans",
    },
    sections: [
      "cover",
      "opening",
      "couple",
      "event",
      "countdown",
      "location",
      "story",
      "gallery",
      "gift",
      "rsvp",
      "guestbook",
      "closing",
    ],
    animationStyle: "fade-up",
    ornamentStyle: "celestial-stars",
  },
  editorial: {
    id: "tpl-editorial",
    slug: "editorial",
    name: "05 Modern Editorial",
    description: "Estetika majalah fashion Haute Vogue bernuansa minimalis arsitektural, tipografi berbobot tinggi kontras, garis hairline presisi, dan layout foto lookbook artistik.",
    colors: {
      primary: "#09090b",
      secondary: "#52525b",
      background: "#f8f8f9",
      foreground: "#09090b",
      accent: "#ebebee",
    },
    typography: {
      heading: "sans",
      body: "sans",
    },
    sections: [
      "cover",
      "opening",
      "couple",
      "event",
      "countdown",
      "location",
      "story",
      "gallery",
      "gift",
      "rsvp",
      "guestbook",
      "closing",
    ],
    animationStyle: "slide",
    ornamentStyle: "editorial-grid",
  },
  botanical: {
    id: "tpl-botanical",
    slug: "botanical",
    name: "06 Romantic Botanical",
    description: "Sentuhan romantis pesta kebun tropis modern dengan aksen dedaunan sage green alami, champagne lembut, frosted glass, dan kelopak melayang dinamis.",
    colors: {
      primary: "#2d4a3e",
      secondary: "#5b7c6f",
      background: "#f5f7f5",
      foreground: "#1b2923",
      accent: "#e3ebe5",
    },
    typography: {
      heading: "serif",
      body: "sans",
    },
    sections: [
      "cover",
      "opening",
      "couple",
      "event",
      "countdown",
      "location",
      "story",
      "gallery",
      "gift",
      "rsvp",
      "guestbook",
      "closing",
    ],
    animationStyle: "smooth",
    ornamentStyle: "botanical-leaves",
  },
};

export function getTemplateConfig(slug: string): TemplateConfig {
  return TEMPLATES[slug] || TEMPLATES.elegant;
}

export function getAllTemplates(): TemplateConfig[] {
  return Object.values(TEMPLATES);
}
